apiVersion: v1
kind: Service
metadata:
  name: opentelemetrycollector
  namespace: monitoring
spec:
  ports:
  - name: grpc-otlp
    port: 4317
    targetPort: 4317
  - name: http-otlp
    port: 4318
    targetPort: 4318
  - name: scrap-prom
    port: 9090
    targetPort: 9090
  selector:
    app.kubernetes.io/name: opentelemetrycollector
  type: ClusterIP